namespace NewCRM
{
    partial class Ana_Sayfa
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Ana_Sayfa));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pbxCikis = new System.Windows.Forms.PictureBox();
            this.btnMesajlar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMusteri = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProfil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblSirket = new Bunifu.UI.WinForms.BunifuLabel();
            this.pbxLogo = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnForum = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnlGecis = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuElipse2 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.lblAd = new System.Windows.Forms.Label();
            this.pbxTakvim = new System.Windows.Forms.PictureBox();
            this.pbxKfoto = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.pnlKapa = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnCikis = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSifre = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPBilgileri = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPersonelBilgileri = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel1.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbxCikis)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbxLogo)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbxTakvim)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbxKfoto)).BeginInit();
            this.pnlKapa.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 50;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.panel1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(-37, -12);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DimGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(303, 836);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.btnPersonelBilgileri);
            this.panel1.Controls.Add(this.bunifuButton1);
            this.panel1.Controls.Add(this.pbxCikis);
            this.panel1.Controls.Add(this.btnMesajlar);
            this.panel1.Controls.Add(this.btnMusteri);
            this.panel1.Controls.Add(this.btnProfil);
            this.panel1.Controls.Add(this.lblSirket);
            this.panel1.Controls.Add(this.pbxLogo);
            this.panel1.Controls.Add(this.btnForum);
            this.panel1.Location = new System.Drawing.Point(35, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(265, 808);
            this.panel1.TabIndex = 0;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Personel";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 30;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(0, 567);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(259, 39);
            this.bunifuButton1.TabIndex = 8;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // pbxCikis
            // 
            this.pbxCikis.Image = ((System.Drawing.Image)(resources.GetObject("pbxCikis.Image")));
            this.pbxCikis.Location = new System.Drawing.Point(204, 756);
            this.pbxCikis.Name = "pbxCikis";
            this.pbxCikis.Size = new System.Drawing.Size(22, 23);
            this.pbxCikis.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbxCikis.TabIndex = 5;
            this.pbxCikis.TabStop = false;
            this.pbxCikis.Click += new System.EventHandler(this.pbxCikis_Click);
            // 
            // btnMesajlar
            // 
            this.btnMesajlar.AllowAnimations = true;
            this.btnMesajlar.AllowMouseEffects = true;
            this.btnMesajlar.AllowToggling = false;
            this.btnMesajlar.AnimationSpeed = 200;
            this.btnMesajlar.AutoGenerateColors = false;
            this.btnMesajlar.AutoRoundBorders = false;
            this.btnMesajlar.AutoSizeLeftIcon = true;
            this.btnMesajlar.AutoSizeRightIcon = true;
            this.btnMesajlar.BackColor = System.Drawing.Color.Transparent;
            this.btnMesajlar.BackColor1 = System.Drawing.Color.Transparent;
            this.btnMesajlar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMesajlar.BackgroundImage")));
            this.btnMesajlar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMesajlar.ButtonText = "Mesajlar";
            this.btnMesajlar.ButtonTextMarginLeft = 0;
            this.btnMesajlar.ColorContrastOnClick = 45;
            this.btnMesajlar.ColorContrastOnHover = 45;
            this.btnMesajlar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnMesajlar.CustomizableEdges = borderEdges3;
            this.btnMesajlar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMesajlar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMesajlar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMesajlar.DisabledForecolor = System.Drawing.Color.White;
            this.btnMesajlar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMesajlar.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnMesajlar.ForeColor = System.Drawing.Color.White;
            this.btnMesajlar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMesajlar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMesajlar.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnMesajlar.IconMarginLeft = 11;
            this.btnMesajlar.IconPadding = 10;
            this.btnMesajlar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMesajlar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMesajlar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMesajlar.IconSize = 25;
            this.btnMesajlar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnMesajlar.IdleBorderRadius = 1;
            this.btnMesajlar.IdleBorderThickness = 1;
            this.btnMesajlar.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnMesajlar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnMesajlar.IdleIconLeftImage")));
            this.btnMesajlar.IdleIconRightImage = null;
            this.btnMesajlar.IndicateFocus = false;
            this.btnMesajlar.Location = new System.Drawing.Point(3, 408);
            this.btnMesajlar.Name = "btnMesajlar";
            this.btnMesajlar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMesajlar.OnDisabledState.BorderRadius = 1;
            this.btnMesajlar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMesajlar.OnDisabledState.BorderThickness = 1;
            this.btnMesajlar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMesajlar.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnMesajlar.OnDisabledState.IconLeftImage = null;
            this.btnMesajlar.OnDisabledState.IconRightImage = null;
            this.btnMesajlar.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnMesajlar.onHoverState.BorderRadius = 1;
            this.btnMesajlar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMesajlar.onHoverState.BorderThickness = 1;
            this.btnMesajlar.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnMesajlar.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnMesajlar.onHoverState.IconLeftImage = null;
            this.btnMesajlar.onHoverState.IconRightImage = null;
            this.btnMesajlar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnMesajlar.OnIdleState.BorderRadius = 1;
            this.btnMesajlar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMesajlar.OnIdleState.BorderThickness = 1;
            this.btnMesajlar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnMesajlar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMesajlar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnMesajlar.OnIdleState.IconLeftImage")));
            this.btnMesajlar.OnIdleState.IconRightImage = null;
            this.btnMesajlar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnMesajlar.OnPressedState.BorderRadius = 1;
            this.btnMesajlar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMesajlar.OnPressedState.BorderThickness = 1;
            this.btnMesajlar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnMesajlar.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnMesajlar.OnPressedState.IconLeftImage = null;
            this.btnMesajlar.OnPressedState.IconRightImage = null;
            this.btnMesajlar.Size = new System.Drawing.Size(262, 39);
            this.btnMesajlar.TabIndex = 6;
            this.btnMesajlar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMesajlar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMesajlar.TextMarginLeft = 0;
            this.btnMesajlar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMesajlar.UseDefaultRadiusAndThickness = true;
            this.btnMesajlar.Click += new System.EventHandler(this.btnMesajlar_Click);
            // 
            // btnMusteri
            // 
            this.btnMusteri.AllowAnimations = true;
            this.btnMusteri.AllowMouseEffects = true;
            this.btnMusteri.AllowToggling = false;
            this.btnMusteri.AnimationSpeed = 200;
            this.btnMusteri.AutoGenerateColors = false;
            this.btnMusteri.AutoRoundBorders = false;
            this.btnMusteri.AutoSizeLeftIcon = true;
            this.btnMusteri.AutoSizeRightIcon = true;
            this.btnMusteri.BackColor = System.Drawing.Color.Transparent;
            this.btnMusteri.BackColor1 = System.Drawing.Color.Transparent;
            this.btnMusteri.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMusteri.BackgroundImage")));
            this.btnMusteri.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMusteri.ButtonText = "               Müşteri Bilgileri";
            this.btnMusteri.ButtonTextMarginLeft = 0;
            this.btnMusteri.ColorContrastOnClick = 45;
            this.btnMusteri.ColorContrastOnHover = 45;
            this.btnMusteri.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnMusteri.CustomizableEdges = borderEdges4;
            this.btnMusteri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMusteri.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMusteri.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMusteri.DisabledForecolor = System.Drawing.Color.White;
            this.btnMusteri.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMusteri.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnMusteri.ForeColor = System.Drawing.Color.White;
            this.btnMusteri.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMusteri.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMusteri.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnMusteri.IconMarginLeft = 11;
            this.btnMusteri.IconPadding = 10;
            this.btnMusteri.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMusteri.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMusteri.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMusteri.IconSize = 30;
            this.btnMusteri.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnMusteri.IdleBorderRadius = 1;
            this.btnMusteri.IdleBorderThickness = 1;
            this.btnMusteri.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnMusteri.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnMusteri.IdleIconLeftImage")));
            this.btnMusteri.IdleIconRightImage = null;
            this.btnMusteri.IndicateFocus = false;
            this.btnMusteri.Location = new System.Drawing.Point(0, 351);
            this.btnMusteri.Name = "btnMusteri";
            this.btnMusteri.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMusteri.OnDisabledState.BorderRadius = 1;
            this.btnMusteri.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMusteri.OnDisabledState.BorderThickness = 1;
            this.btnMusteri.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnMusteri.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnMusteri.OnDisabledState.IconLeftImage = null;
            this.btnMusteri.OnDisabledState.IconRightImage = null;
            this.btnMusteri.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnMusteri.onHoverState.BorderRadius = 1;
            this.btnMusteri.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMusteri.onHoverState.BorderThickness = 1;
            this.btnMusteri.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnMusteri.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnMusteri.onHoverState.IconLeftImage = null;
            this.btnMusteri.onHoverState.IconRightImage = null;
            this.btnMusteri.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnMusteri.OnIdleState.BorderRadius = 1;
            this.btnMusteri.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMusteri.OnIdleState.BorderThickness = 1;
            this.btnMusteri.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnMusteri.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMusteri.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnMusteri.OnIdleState.IconLeftImage")));
            this.btnMusteri.OnIdleState.IconRightImage = null;
            this.btnMusteri.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnMusteri.OnPressedState.BorderRadius = 1;
            this.btnMusteri.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMusteri.OnPressedState.BorderThickness = 1;
            this.btnMusteri.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnMusteri.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnMusteri.OnPressedState.IconLeftImage = null;
            this.btnMusteri.OnPressedState.IconRightImage = null;
            this.btnMusteri.Size = new System.Drawing.Size(262, 39);
            this.btnMusteri.TabIndex = 3;
            this.btnMusteri.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMusteri.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMusteri.TextMarginLeft = 0;
            this.btnMusteri.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMusteri.UseDefaultRadiusAndThickness = true;
            this.btnMusteri.Click += new System.EventHandler(this.btnMusteri_Click);
            // 
            // btnProfil
            // 
            this.btnProfil.AllowAnimations = true;
            this.btnProfil.AllowMouseEffects = true;
            this.btnProfil.AllowToggling = false;
            this.btnProfil.AnimationSpeed = 200;
            this.btnProfil.AutoGenerateColors = false;
            this.btnProfil.AutoRoundBorders = false;
            this.btnProfil.AutoSizeLeftIcon = true;
            this.btnProfil.AutoSizeRightIcon = true;
            this.btnProfil.BackColor = System.Drawing.Color.Transparent;
            this.btnProfil.BackColor1 = System.Drawing.Color.Transparent;
            this.btnProfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProfil.BackgroundImage")));
            this.btnProfil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProfil.ButtonText = "Profil";
            this.btnProfil.ButtonTextMarginLeft = 0;
            this.btnProfil.ColorContrastOnClick = 45;
            this.btnProfil.ColorContrastOnHover = 45;
            this.btnProfil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnProfil.CustomizableEdges = borderEdges5;
            this.btnProfil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProfil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnProfil.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnProfil.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProfil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProfil.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnProfil.ForeColor = System.Drawing.Color.White;
            this.btnProfil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProfil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProfil.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnProfil.IconMarginLeft = 11;
            this.btnProfil.IconPadding = 10;
            this.btnProfil.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProfil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProfil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProfil.IconSize = 30;
            this.btnProfil.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnProfil.IdleBorderRadius = 1;
            this.btnProfil.IdleBorderThickness = 1;
            this.btnProfil.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnProfil.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnProfil.IdleIconLeftImage")));
            this.btnProfil.IdleIconRightImage = null;
            this.btnProfil.IndicateFocus = false;
            this.btnProfil.Location = new System.Drawing.Point(3, 294);
            this.btnProfil.Name = "btnProfil";
            this.btnProfil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnProfil.OnDisabledState.BorderRadius = 1;
            this.btnProfil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProfil.OnDisabledState.BorderThickness = 1;
            this.btnProfil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnProfil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProfil.OnDisabledState.IconLeftImage = null;
            this.btnProfil.OnDisabledState.IconRightImage = null;
            this.btnProfil.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnProfil.onHoverState.BorderRadius = 1;
            this.btnProfil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProfil.onHoverState.BorderThickness = 1;
            this.btnProfil.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProfil.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.btnProfil.onHoverState.IconLeftImage = null;
            this.btnProfil.onHoverState.IconRightImage = null;
            this.btnProfil.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnProfil.OnIdleState.BorderRadius = 1;
            this.btnProfil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProfil.OnIdleState.BorderThickness = 1;
            this.btnProfil.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnProfil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProfil.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnProfil.OnIdleState.IconLeftImage")));
            this.btnProfil.OnIdleState.IconRightImage = null;
            this.btnProfil.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnProfil.OnPressedState.BorderRadius = 1;
            this.btnProfil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProfil.OnPressedState.BorderThickness = 1;
            this.btnProfil.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnProfil.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.btnProfil.OnPressedState.IconLeftImage = null;
            this.btnProfil.OnPressedState.IconRightImage = null;
            this.btnProfil.Size = new System.Drawing.Size(259, 39);
            this.btnProfil.TabIndex = 2;
            this.btnProfil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProfil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProfil.TextMarginLeft = 0;
            this.btnProfil.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProfil.UseDefaultRadiusAndThickness = true;
            this.btnProfil.Click += new System.EventHandler(this.btnProfil_Click);
            // 
            // lblSirket
            // 
            this.lblSirket.AllowParentOverrides = false;
            this.lblSirket.AutoEllipsis = false;
            this.lblSirket.CursorType = null;
            this.lblSirket.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.lblSirket.ForeColor = System.Drawing.Color.White;
            this.lblSirket.Location = new System.Drawing.Point(47, 187);
            this.lblSirket.Name = "lblSirket";
            this.lblSirket.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSirket.Size = new System.Drawing.Size(138, 45);
            this.lblSirket.TabIndex = 1;
            this.lblSirket.Text = "Şirket Adı";
            this.lblSirket.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSirket.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pbxLogo
            // 
            this.pbxLogo.AllowFocused = false;
            this.pbxLogo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbxLogo.AutoSizeHeight = true;
            this.pbxLogo.BorderRadius = 59;
            this.pbxLogo.Image = ((System.Drawing.Image)(resources.GetObject("pbxLogo.Image")));
            this.pbxLogo.IsCircle = true;
            this.pbxLogo.Location = new System.Drawing.Point(66, 50);
            this.pbxLogo.Name = "pbxLogo";
            this.pbxLogo.Size = new System.Drawing.Size(119, 119);
            this.pbxLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbxLogo.TabIndex = 0;
            this.pbxLogo.TabStop = false;
            this.pbxLogo.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // btnForum
            // 
            this.btnForum.AllowAnimations = true;
            this.btnForum.AllowMouseEffects = true;
            this.btnForum.AllowToggling = false;
            this.btnForum.AnimationSpeed = 200;
            this.btnForum.AutoGenerateColors = false;
            this.btnForum.AutoRoundBorders = false;
            this.btnForum.AutoSizeLeftIcon = true;
            this.btnForum.AutoSizeRightIcon = true;
            this.btnForum.BackColor = System.Drawing.Color.Transparent;
            this.btnForum.BackColor1 = System.Drawing.Color.Transparent;
            this.btnForum.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnForum.BackgroundImage")));
            this.btnForum.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnForum.ButtonText = "Takvim";
            this.btnForum.ButtonTextMarginLeft = 0;
            this.btnForum.ColorContrastOnClick = 45;
            this.btnForum.ColorContrastOnHover = 45;
            this.btnForum.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnForum.CustomizableEdges = borderEdges6;
            this.btnForum.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnForum.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnForum.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnForum.DisabledForecolor = System.Drawing.Color.White;
            this.btnForum.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnForum.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnForum.ForeColor = System.Drawing.Color.White;
            this.btnForum.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnForum.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnForum.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnForum.IconMarginLeft = 11;
            this.btnForum.IconPadding = 10;
            this.btnForum.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnForum.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnForum.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnForum.IconSize = 25;
            this.btnForum.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnForum.IdleBorderRadius = 1;
            this.btnForum.IdleBorderThickness = 1;
            this.btnForum.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnForum.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnForum.IdleIconLeftImage")));
            this.btnForum.IdleIconRightImage = null;
            this.btnForum.IndicateFocus = false;
            this.btnForum.Location = new System.Drawing.Point(0, 465);
            this.btnForum.Name = "btnForum";
            this.btnForum.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnForum.OnDisabledState.BorderRadius = 1;
            this.btnForum.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnForum.OnDisabledState.BorderThickness = 1;
            this.btnForum.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnForum.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnForum.OnDisabledState.IconLeftImage = null;
            this.btnForum.OnDisabledState.IconRightImage = null;
            this.btnForum.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnForum.onHoverState.BorderRadius = 1;
            this.btnForum.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnForum.onHoverState.BorderThickness = 1;
            this.btnForum.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnForum.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnForum.onHoverState.IconLeftImage = null;
            this.btnForum.onHoverState.IconRightImage = null;
            this.btnForum.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnForum.OnIdleState.BorderRadius = 1;
            this.btnForum.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnForum.OnIdleState.BorderThickness = 1;
            this.btnForum.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnForum.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnForum.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnForum.OnIdleState.IconLeftImage")));
            this.btnForum.OnIdleState.IconRightImage = null;
            this.btnForum.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnForum.OnPressedState.BorderRadius = 1;
            this.btnForum.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnForum.OnPressedState.BorderThickness = 1;
            this.btnForum.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnForum.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnForum.OnPressedState.IconLeftImage = null;
            this.btnForum.OnPressedState.IconRightImage = null;
            this.btnForum.Size = new System.Drawing.Size(262, 39);
            this.btnForum.TabIndex = 7;
            this.btnForum.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnForum.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnForum.TextMarginLeft = 0;
            this.btnForum.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnForum.UseDefaultRadiusAndThickness = true;
            this.btnForum.Click += new System.EventHandler(this.btnForum_Click_1);
            // 
            // pnlGecis
            // 
            this.pnlGecis.BackColor = System.Drawing.Color.Transparent;
            this.pnlGecis.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.pnlGecis.BorderRadius = 15;
            this.pnlGecis.BorderThickness = 1;
            this.pnlGecis.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlGecis.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlGecis.Location = new System.Drawing.Point(272, 100);
            this.pnlGecis.Name = "pnlGecis";
            this.pnlGecis.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.pnlGecis.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.pnlGecis.ShadowColor = System.Drawing.Color.Empty;
            this.pnlGecis.ShadowDept = 2;
            this.pnlGecis.ShadowDepth = 10;
            this.pnlGecis.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlGecis.ShadowTopLeftVisible = false;
            this.pnlGecis.Size = new System.Drawing.Size(1227, 699);
            this.pnlGecis.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlGecis.TabIndex = 2;
            // 
            // bunifuElipse2
            // 
            this.bunifuElipse2.ElipseRadius = 25;
            this.bunifuElipse2.TargetControl = this;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 80;
            this.bunifuGradientPanel1.Controls.Add(this.pictureBox1);
            this.bunifuGradientPanel1.Controls.Add(this.lblAd);
            this.bunifuGradientPanel1.Controls.Add(this.pbxTakvim);
            this.bunifuGradientPanel1.Controls.Add(this.pbxKfoto);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(793, -31);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(726, 125);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(690, 31);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(26, 28);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 5;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // lblAd
            // 
            this.lblAd.AutoSize = true;
            this.lblAd.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.lblAd.ForeColor = System.Drawing.Color.White;
            this.lblAd.Location = new System.Drawing.Point(483, 99);
            this.lblAd.Name = "lblAd";
            this.lblAd.Size = new System.Drawing.Size(44, 16);
            this.lblAd.TabIndex = 4;
            this.lblAd.Text = "label1";
            // 
            // pbxTakvim
            // 
            this.pbxTakvim.Image = ((System.Drawing.Image)(resources.GetObject("pbxTakvim.Image")));
            this.pbxTakvim.Location = new System.Drawing.Point(436, 92);
            this.pbxTakvim.Name = "pbxTakvim";
            this.pbxTakvim.Size = new System.Drawing.Size(22, 23);
            this.pbxTakvim.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbxTakvim.TabIndex = 3;
            this.pbxTakvim.TabStop = false;
            this.pbxTakvim.Click += new System.EventHandler(this.pbxTakvim_Click);
            // 
            // pbxKfoto
            // 
            this.pbxKfoto.AllowFocused = false;
            this.pbxKfoto.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbxKfoto.AutoSizeHeight = true;
            this.pbxKfoto.BorderRadius = 38;
            this.pbxKfoto.Image = ((System.Drawing.Image)(resources.GetObject("pbxKfoto.Image")));
            this.pbxKfoto.IsCircle = true;
            this.pbxKfoto.Location = new System.Drawing.Point(614, 43);
            this.pbxKfoto.Name = "pbxKfoto";
            this.pbxKfoto.Size = new System.Drawing.Size(77, 77);
            this.pbxKfoto.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbxKfoto.TabIndex = 2;
            this.pbxKfoto.TabStop = false;
            this.pbxKfoto.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.pbxKfoto.Click += new System.EventHandler(this.pbxKfoto_Click);
            // 
            // pnlKapa
            // 
            this.pnlKapa.BackColor = System.Drawing.Color.Transparent;
            this.pnlKapa.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.pnlKapa.BorderRadius = 1;
            this.pnlKapa.BorderThickness = 1;
            this.pnlKapa.Controls.Add(this.btnCikis);
            this.pnlKapa.Controls.Add(this.btnSifre);
            this.pnlKapa.Controls.Add(this.btnPBilgileri);
            this.pnlKapa.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlKapa.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlKapa.Location = new System.Drawing.Point(1116, 83);
            this.pnlKapa.Name = "pnlKapa";
            this.pnlKapa.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.pnlKapa.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(50)))), ((int)(((byte)(188)))));
            this.pnlKapa.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(151)))), ((int)(((byte)(249)))));
            this.pnlKapa.ShadowDept = 2;
            this.pnlKapa.ShadowDepth = 5;
            this.pnlKapa.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.pnlKapa.ShadowTopLeftVisible = false;
            this.pnlKapa.Size = new System.Drawing.Size(370, 187);
            this.pnlKapa.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlKapa.TabIndex = 3;
            this.pnlKapa.Visible = false;
            // 
            // btnCikis
            // 
            this.btnCikis.AllowAnimations = true;
            this.btnCikis.AllowMouseEffects = true;
            this.btnCikis.AllowToggling = false;
            this.btnCikis.AnimationSpeed = 200;
            this.btnCikis.AutoGenerateColors = false;
            this.btnCikis.AutoRoundBorders = false;
            this.btnCikis.AutoSizeLeftIcon = true;
            this.btnCikis.AutoSizeRightIcon = true;
            this.btnCikis.BackColor = System.Drawing.Color.Transparent;
            this.btnCikis.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCikis.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCikis.BackgroundImage")));
            this.btnCikis.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCikis.ButtonText = "Çıkış Yap";
            this.btnCikis.ButtonTextMarginLeft = 0;
            this.btnCikis.ColorContrastOnClick = 45;
            this.btnCikis.ColorContrastOnHover = 45;
            this.btnCikis.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCikis.CustomizableEdges = borderEdges7;
            this.btnCikis.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCikis.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnCikis.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnCikis.DisabledForecolor = System.Drawing.Color.White;
            this.btnCikis.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCikis.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnCikis.ForeColor = System.Drawing.Color.White;
            this.btnCikis.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCikis.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCikis.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnCikis.IconMarginLeft = 11;
            this.btnCikis.IconPadding = 10;
            this.btnCikis.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCikis.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCikis.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCikis.IconSize = 30;
            this.btnCikis.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCikis.IdleBorderRadius = 1;
            this.btnCikis.IdleBorderThickness = 1;
            this.btnCikis.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCikis.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCikis.IdleIconLeftImage")));
            this.btnCikis.IdleIconRightImage = null;
            this.btnCikis.IndicateFocus = false;
            this.btnCikis.Location = new System.Drawing.Point(3, 120);
            this.btnCikis.Name = "btnCikis";
            this.btnCikis.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnCikis.OnDisabledState.BorderRadius = 1;
            this.btnCikis.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCikis.OnDisabledState.BorderThickness = 1;
            this.btnCikis.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnCikis.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnCikis.OnDisabledState.IconLeftImage = null;
            this.btnCikis.OnDisabledState.IconRightImage = null;
            this.btnCikis.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnCikis.onHoverState.BorderRadius = 1;
            this.btnCikis.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCikis.onHoverState.BorderThickness = 1;
            this.btnCikis.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnCikis.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnCikis.onHoverState.IconLeftImage = null;
            this.btnCikis.onHoverState.IconRightImage = null;
            this.btnCikis.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCikis.OnIdleState.BorderRadius = 1;
            this.btnCikis.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCikis.OnIdleState.BorderThickness = 1;
            this.btnCikis.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCikis.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCikis.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCikis.OnIdleState.IconLeftImage")));
            this.btnCikis.OnIdleState.IconRightImage = null;
            this.btnCikis.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnCikis.OnPressedState.BorderRadius = 1;
            this.btnCikis.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCikis.OnPressedState.BorderThickness = 1;
            this.btnCikis.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnCikis.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnCikis.OnPressedState.IconLeftImage = null;
            this.btnCikis.OnPressedState.IconRightImage = null;
            this.btnCikis.Size = new System.Drawing.Size(370, 39);
            this.btnCikis.TabIndex = 6;
            this.btnCikis.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCikis.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCikis.TextMarginLeft = 0;
            this.btnCikis.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCikis.UseDefaultRadiusAndThickness = true;
            this.btnCikis.Click += new System.EventHandler(this.btnCikis_Click);
            // 
            // btnSifre
            // 
            this.btnSifre.AllowAnimations = true;
            this.btnSifre.AllowMouseEffects = true;
            this.btnSifre.AllowToggling = false;
            this.btnSifre.AnimationSpeed = 200;
            this.btnSifre.AutoGenerateColors = false;
            this.btnSifre.AutoRoundBorders = false;
            this.btnSifre.AutoSizeLeftIcon = true;
            this.btnSifre.AutoSizeRightIcon = true;
            this.btnSifre.BackColor = System.Drawing.Color.Transparent;
            this.btnSifre.BackColor1 = System.Drawing.Color.Transparent;
            this.btnSifre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSifre.BackgroundImage")));
            this.btnSifre.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSifre.ButtonText = "Şifre Değiştir";
            this.btnSifre.ButtonTextMarginLeft = 0;
            this.btnSifre.ColorContrastOnClick = 45;
            this.btnSifre.ColorContrastOnHover = 45;
            this.btnSifre.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnSifre.CustomizableEdges = borderEdges8;
            this.btnSifre.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSifre.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnSifre.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnSifre.DisabledForecolor = System.Drawing.Color.White;
            this.btnSifre.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSifre.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnSifre.ForeColor = System.Drawing.Color.White;
            this.btnSifre.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSifre.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSifre.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnSifre.IconMarginLeft = 11;
            this.btnSifre.IconPadding = 10;
            this.btnSifre.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSifre.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSifre.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSifre.IconSize = 60;
            this.btnSifre.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnSifre.IdleBorderRadius = 1;
            this.btnSifre.IdleBorderThickness = 1;
            this.btnSifre.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnSifre.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSifre.IdleIconLeftImage")));
            this.btnSifre.IdleIconRightImage = null;
            this.btnSifre.IndicateFocus = false;
            this.btnSifre.Location = new System.Drawing.Point(3, 73);
            this.btnSifre.Name = "btnSifre";
            this.btnSifre.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnSifre.OnDisabledState.BorderRadius = 1;
            this.btnSifre.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSifre.OnDisabledState.BorderThickness = 1;
            this.btnSifre.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(155)))), ((int)(((byte)(255)))));
            this.btnSifre.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnSifre.OnDisabledState.IconLeftImage = null;
            this.btnSifre.OnDisabledState.IconRightImage = null;
            this.btnSifre.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnSifre.onHoverState.BorderRadius = 1;
            this.btnSifre.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSifre.onHoverState.BorderThickness = 1;
            this.btnSifre.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnSifre.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnSifre.onHoverState.IconLeftImage = null;
            this.btnSifre.onHoverState.IconRightImage = null;
            this.btnSifre.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSifre.OnIdleState.BorderRadius = 1;
            this.btnSifre.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSifre.OnIdleState.BorderThickness = 1;
            this.btnSifre.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnSifre.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSifre.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSifre.OnIdleState.IconLeftImage")));
            this.btnSifre.OnIdleState.IconRightImage = null;
            this.btnSifre.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnSifre.OnPressedState.BorderRadius = 1;
            this.btnSifre.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSifre.OnPressedState.BorderThickness = 1;
            this.btnSifre.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnSifre.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(113)))), ((int)(((byte)(116)))));
            this.btnSifre.OnPressedState.IconLeftImage = null;
            this.btnSifre.OnPressedState.IconRightImage = null;
            this.btnSifre.Size = new System.Drawing.Size(370, 39);
            this.btnSifre.TabIndex = 5;
            this.btnSifre.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSifre.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSifre.TextMarginLeft = 0;
            this.btnSifre.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSifre.UseDefaultRadiusAndThickness = true;
            this.btnSifre.Click += new System.EventHandler(this.btnSifre_Click);
            // 
            // btnPBilgileri
            // 
            this.btnPBilgileri.AllowAnimations = true;
            this.btnPBilgileri.AllowMouseEffects = true;
            this.btnPBilgileri.AllowToggling = false;
            this.btnPBilgileri.AnimationSpeed = 200;
            this.btnPBilgileri.AutoGenerateColors = false;
            this.btnPBilgileri.AutoRoundBorders = false;
            this.btnPBilgileri.AutoSizeLeftIcon = true;
            this.btnPBilgileri.AutoSizeRightIcon = true;
            this.btnPBilgileri.BackColor = System.Drawing.Color.Transparent;
            this.btnPBilgileri.BackColor1 = System.Drawing.Color.Transparent;
            this.btnPBilgileri.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPBilgileri.BackgroundImage")));
            this.btnPBilgileri.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPBilgileri.ButtonText = "Personel Bilgileri";
            this.btnPBilgileri.ButtonTextMarginLeft = 0;
            this.btnPBilgileri.ColorContrastOnClick = 45;
            this.btnPBilgileri.ColorContrastOnHover = 45;
            this.btnPBilgileri.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnPBilgileri.CustomizableEdges = borderEdges9;
            this.btnPBilgileri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPBilgileri.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPBilgileri.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPBilgileri.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPBilgileri.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPBilgileri.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnPBilgileri.ForeColor = System.Drawing.Color.White;
            this.btnPBilgileri.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPBilgileri.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPBilgileri.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnPBilgileri.IconMarginLeft = 11;
            this.btnPBilgileri.IconPadding = 10;
            this.btnPBilgileri.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPBilgileri.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPBilgileri.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPBilgileri.IconSize = 30;
            this.btnPBilgileri.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnPBilgileri.IdleBorderRadius = 1;
            this.btnPBilgileri.IdleBorderThickness = 1;
            this.btnPBilgileri.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnPBilgileri.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPBilgileri.IdleIconLeftImage")));
            this.btnPBilgileri.IdleIconRightImage = null;
            this.btnPBilgileri.IndicateFocus = false;
            this.btnPBilgileri.Location = new System.Drawing.Point(3, 25);
            this.btnPBilgileri.Name = "btnPBilgileri";
            this.btnPBilgileri.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPBilgileri.OnDisabledState.BorderRadius = 1;
            this.btnPBilgileri.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPBilgileri.OnDisabledState.BorderThickness = 1;
            this.btnPBilgileri.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPBilgileri.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPBilgileri.OnDisabledState.IconLeftImage = null;
            this.btnPBilgileri.OnDisabledState.IconRightImage = null;
            this.btnPBilgileri.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnPBilgileri.onHoverState.BorderRadius = 1;
            this.btnPBilgileri.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPBilgileri.onHoverState.BorderThickness = 1;
            this.btnPBilgileri.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnPBilgileri.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.btnPBilgileri.onHoverState.IconLeftImage = null;
            this.btnPBilgileri.onHoverState.IconRightImage = null;
            this.btnPBilgileri.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPBilgileri.OnIdleState.BorderRadius = 1;
            this.btnPBilgileri.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPBilgileri.OnIdleState.BorderThickness = 1;
            this.btnPBilgileri.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnPBilgileri.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPBilgileri.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPBilgileri.OnIdleState.IconLeftImage")));
            this.btnPBilgileri.OnIdleState.IconRightImage = null;
            this.btnPBilgileri.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPBilgileri.OnPressedState.BorderRadius = 1;
            this.btnPBilgileri.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPBilgileri.OnPressedState.BorderThickness = 1;
            this.btnPBilgileri.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPBilgileri.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.btnPBilgileri.OnPressedState.IconLeftImage = null;
            this.btnPBilgileri.OnPressedState.IconRightImage = null;
            this.btnPBilgileri.Size = new System.Drawing.Size(367, 39);
            this.btnPBilgileri.TabIndex = 4;
            this.btnPBilgileri.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPBilgileri.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPBilgileri.TextMarginLeft = 0;
            this.btnPBilgileri.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPBilgileri.UseDefaultRadiusAndThickness = true;
            this.btnPBilgileri.Click += new System.EventHandler(this.btnPBilgileri_Click);
            // 
            // btnPersonelBilgileri
            // 
            this.btnPersonelBilgileri.AllowAnimations = true;
            this.btnPersonelBilgileri.AllowMouseEffects = true;
            this.btnPersonelBilgileri.AllowToggling = false;
            this.btnPersonelBilgileri.AnimationSpeed = 200;
            this.btnPersonelBilgileri.AutoGenerateColors = false;
            this.btnPersonelBilgileri.AutoRoundBorders = false;
            this.btnPersonelBilgileri.AutoSizeLeftIcon = true;
            this.btnPersonelBilgileri.AutoSizeRightIcon = true;
            this.btnPersonelBilgileri.BackColor = System.Drawing.Color.Transparent;
            this.btnPersonelBilgileri.BackColor1 = System.Drawing.Color.Transparent;
            this.btnPersonelBilgileri.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPersonelBilgileri.BackgroundImage")));
            this.btnPersonelBilgileri.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPersonelBilgileri.ButtonText = "Personel Bilgileri";
            this.btnPersonelBilgileri.ButtonTextMarginLeft = 0;
            this.btnPersonelBilgileri.ColorContrastOnClick = 45;
            this.btnPersonelBilgileri.ColorContrastOnHover = 45;
            this.btnPersonelBilgileri.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnPersonelBilgileri.CustomizableEdges = borderEdges1;
            this.btnPersonelBilgileri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPersonelBilgileri.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPersonelBilgileri.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPersonelBilgileri.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPersonelBilgileri.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPersonelBilgileri.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnPersonelBilgileri.ForeColor = System.Drawing.Color.White;
            this.btnPersonelBilgileri.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPersonelBilgileri.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPersonelBilgileri.IconLeftPadding = new System.Windows.Forms.Padding(55, 3, 3, 3);
            this.btnPersonelBilgileri.IconMarginLeft = 11;
            this.btnPersonelBilgileri.IconPadding = 10;
            this.btnPersonelBilgileri.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPersonelBilgileri.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPersonelBilgileri.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPersonelBilgileri.IconSize = 30;
            this.btnPersonelBilgileri.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnPersonelBilgileri.IdleBorderRadius = 1;
            this.btnPersonelBilgileri.IdleBorderThickness = 1;
            this.btnPersonelBilgileri.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnPersonelBilgileri.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPersonelBilgileri.IdleIconLeftImage")));
            this.btnPersonelBilgileri.IdleIconRightImage = null;
            this.btnPersonelBilgileri.IndicateFocus = false;
            this.btnPersonelBilgileri.Location = new System.Drawing.Point(0, 518);
            this.btnPersonelBilgileri.Name = "btnPersonelBilgileri";
            this.btnPersonelBilgileri.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPersonelBilgileri.OnDisabledState.BorderRadius = 1;
            this.btnPersonelBilgileri.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPersonelBilgileri.OnDisabledState.BorderThickness = 1;
            this.btnPersonelBilgileri.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPersonelBilgileri.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPersonelBilgileri.OnDisabledState.IconLeftImage = null;
            this.btnPersonelBilgileri.OnDisabledState.IconRightImage = null;
            this.btnPersonelBilgileri.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.btnPersonelBilgileri.onHoverState.BorderRadius = 1;
            this.btnPersonelBilgileri.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPersonelBilgileri.onHoverState.BorderThickness = 1;
            this.btnPersonelBilgileri.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnPersonelBilgileri.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.btnPersonelBilgileri.onHoverState.IconLeftImage = null;
            this.btnPersonelBilgileri.onHoverState.IconRightImage = null;
            this.btnPersonelBilgileri.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPersonelBilgileri.OnIdleState.BorderRadius = 1;
            this.btnPersonelBilgileri.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPersonelBilgileri.OnIdleState.BorderThickness = 1;
            this.btnPersonelBilgileri.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnPersonelBilgileri.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPersonelBilgileri.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.OnIdleState.IconLeftImage")));
            this.btnPersonelBilgileri.OnIdleState.IconRightImage = null;
            this.btnPersonelBilgileri.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPersonelBilgileri.OnPressedState.BorderRadius = 1;
            this.btnPersonelBilgileri.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPersonelBilgileri.OnPressedState.BorderThickness = 1;
            this.btnPersonelBilgileri.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(215)))), ((int)(((byte)(255)))));
            this.btnPersonelBilgileri.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(94)))), ((int)(((byte)(111)))));
            this.btnPersonelBilgileri.OnPressedState.IconLeftImage = null;
            this.btnPersonelBilgileri.OnPressedState.IconRightImage = null;
            this.btnPersonelBilgileri.Size = new System.Drawing.Size(259, 39);
            this.btnPersonelBilgileri.TabIndex = 9;
            this.btnPersonelBilgileri.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPersonelBilgileri.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPersonelBilgileri.TextMarginLeft = 0;
            this.btnPersonelBilgileri.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.btnPersonelBilgileri.UseDefaultRadiusAndThickness = true;
            this.btnPersonelBilgileri.Visible = false;
            this.btnPersonelBilgileri.Click += new System.EventHandler(this.btnPersonelBilgileri_Click);
            // 
            // Ana_Sayfa
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1511, 811);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Controls.Add(this.pnlKapa);
            this.Controls.Add(this.pnlGecis);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Ana_Sayfa";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Ana_Sayfa";
            this.Load += new System.EventHandler(this.Ana_Sayfa_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbxCikis)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbxLogo)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbxTakvim)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbxKfoto)).EndInit();
            this.pnlKapa.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnForum;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMesajlar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMusteri;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProfil;
        private Bunifu.UI.WinForms.BunifuLabel lblSirket;
        private Bunifu.UI.WinForms.BunifuPictureBox pbxLogo;
        private System.Windows.Forms.PictureBox pbxTakvim;
        private Bunifu.UI.WinForms.BunifuPictureBox pbxKfoto;
        protected System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox pbxCikis;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse2;
        private System.Windows.Forms.Label lblAd;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuShadowPanel pnlKapa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCikis;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSifre;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPBilgileri;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlGecis;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPersonelBilgileri;
    }
}