<?xml version="1.0" encoding="utf-8"?><Database Name="CRM1" Class="DataClassesMusteriBilgileriDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ZEHRA\SQLEXPRESS;Initial Catalog=CRM1;Integrated Security=True" SettingsObjectName="NewCRM.Properties.Settings" SettingsPropertyName="CRM1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Notlar" Member="Notlar">
    <Type Name="Notlar">
      <Column Name="n_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ekleyen_tc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="icerik" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="musteri_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="eklenen_tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="proje_adi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Musteri_Notlar" Member="Musteri" ThisKey="musteri_id" OtherKey="m_id" Type="Musteri" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Musteri" Member="Musteri">
    <Type Name="Musteri">
      <Column Name="m_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="soyad" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ep" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="calistigi_yer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="pozisyonu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ilk_tarih" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="son_tarih" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="durum" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="proje_adi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="projeyi_yoneten" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Musteri_Notlar" Member="Notlar" ThisKey="m_id" OtherKey="musteri_id" Type="Notlar" />
    </Type>
  </Table>
  <Table Name="dbo.PersonelTablosu" Member="PersonelTablosu">
    <Type Name="PersonelTablosu">
      <Column Name="p_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tc" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soyad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cinsiyet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dogum_tarihi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pozisyonu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="tel2" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ep1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ep2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="adres" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="il" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ilce" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="yetki" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sifre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cv" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="posta_kodu" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TakvimTablosu" Member="TakvimTablosu">
    <Type Name="TakvimTablosu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tarih" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="proje_adi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="musteri_adi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icerik" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="kaydeden" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
</Database>