#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCRM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM1")]
	public partial class DataClassesMusteriBilgileriDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMusteri(Musteri instance);
    partial void UpdateMusteri(Musteri instance);
    partial void DeleteMusteri(Musteri instance);
    partial void InsertPersonelTablosu(PersonelTablosu instance);
    partial void UpdatePersonelTablosu(PersonelTablosu instance);
    partial void DeletePersonelTablosu(PersonelTablosu instance);
    #endregion
		
		public DataClassesMusteriBilgileriDataContext() : 
				base(global::NewCRM.Properties.Settings.Default.CRM1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMusteriBilgileriDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMusteriBilgileriDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMusteriBilgileriDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMusteriBilgileriDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Musteri> Musteri
		{
			get
			{
				return this.GetTable<Musteri>();
			}
		}
		
		public System.Data.Linq.Table<Notlar> Notlar
		{
			get
			{
				return this.GetTable<Notlar>();
			}
		}
		
		public System.Data.Linq.Table<PersonelTablosu> PersonelTablosu
		{
			get
			{
				return this.GetTable<PersonelTablosu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteri")]
	public partial class Musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _m_id;
		
		private string _ad;
		
		private string _soyad;
		
		private string _ep;
		
		private string _tel;
		
		private string _calistigi_yer;
		
		private string _pozisyonu;
		
		private System.DateTime _ilk_tarih;
		
		private System.DateTime _son_tarih;
		
		private string _durum;
		
		private string _proje_adi;
		
		private int _projeyi_yoneten;
		
		private System.Data.Linq.Binary _foto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onm_idChanging(int value);
    partial void Onm_idChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void OnepChanging(string value);
    partial void OnepChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void Oncalistigi_yerChanging(string value);
    partial void Oncalistigi_yerChanged();
    partial void OnpozisyonuChanging(string value);
    partial void OnpozisyonuChanged();
    partial void Onilk_tarihChanging(System.DateTime value);
    partial void Onilk_tarihChanged();
    partial void Onson_tarihChanging(System.DateTime value);
    partial void Onson_tarihChanged();
    partial void OndurumChanging(string value);
    partial void OndurumChanged();
    partial void Onproje_adiChanging(string value);
    partial void Onproje_adiChanged();
    partial void Onprojeyi_yonetenChanging(int value);
    partial void Onprojeyi_yonetenChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    #endregion
		
		public Musteri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int m_id
		{
			get
			{
				return this._m_id;
			}
			set
			{
				if ((this._m_id != value))
				{
					this.Onm_idChanging(value);
					this.SendPropertyChanging();
					this._m_id = value;
					this.SendPropertyChanged("m_id");
					this.Onm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this.OnsoyadChanging(value);
					this.SendPropertyChanging();
					this._soyad = value;
					this.SendPropertyChanged("soyad");
					this.OnsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ep", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ep
		{
			get
			{
				return this._ep;
			}
			set
			{
				if ((this._ep != value))
				{
					this.OnepChanging(value);
					this.SendPropertyChanging();
					this._ep = value;
					this.SendPropertyChanged("ep");
					this.OnepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calistigi_yer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string calistigi_yer
		{
			get
			{
				return this._calistigi_yer;
			}
			set
			{
				if ((this._calistigi_yer != value))
				{
					this.Oncalistigi_yerChanging(value);
					this.SendPropertyChanging();
					this._calistigi_yer = value;
					this.SendPropertyChanged("calistigi_yer");
					this.Oncalistigi_yerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pozisyonu", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string pozisyonu
		{
			get
			{
				return this._pozisyonu;
			}
			set
			{
				if ((this._pozisyonu != value))
				{
					this.OnpozisyonuChanging(value);
					this.SendPropertyChanging();
					this._pozisyonu = value;
					this.SendPropertyChanged("pozisyonu");
					this.OnpozisyonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilk_tarih", DbType="DateTime NOT NULL")]
		public System.DateTime ilk_tarih
		{
			get
			{
				return this._ilk_tarih;
			}
			set
			{
				if ((this._ilk_tarih != value))
				{
					this.Onilk_tarihChanging(value);
					this.SendPropertyChanging();
					this._ilk_tarih = value;
					this.SendPropertyChanged("ilk_tarih");
					this.Onilk_tarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_son_tarih", DbType="DateTime NOT NULL")]
		public System.DateTime son_tarih
		{
			get
			{
				return this._son_tarih;
			}
			set
			{
				if ((this._son_tarih != value))
				{
					this.Onson_tarihChanging(value);
					this.SendPropertyChanging();
					this._son_tarih = value;
					this.SendPropertyChanged("son_tarih");
					this.Onson_tarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string durum
		{
			get
			{
				return this._durum;
			}
			set
			{
				if ((this._durum != value))
				{
					this.OndurumChanging(value);
					this.SendPropertyChanging();
					this._durum = value;
					this.SendPropertyChanged("durum");
					this.OndurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proje_adi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string proje_adi
		{
			get
			{
				return this._proje_adi;
			}
			set
			{
				if ((this._proje_adi != value))
				{
					this.Onproje_adiChanging(value);
					this.SendPropertyChanging();
					this._proje_adi = value;
					this.SendPropertyChanged("proje_adi");
					this.Onproje_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projeyi_yoneten", DbType="Int NOT NULL")]
		public int projeyi_yoneten
		{
			get
			{
				return this._projeyi_yoneten;
			}
			set
			{
				if ((this._projeyi_yoneten != value))
				{
					this.Onprojeyi_yonetenChanging(value);
					this.SendPropertyChanging();
					this._projeyi_yoneten = value;
					this.SendPropertyChanged("projeyi_yoneten");
					this.Onprojeyi_yonetenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notlar")]
	public partial class Notlar
	{
		
		private string _n_id;
		
		private System.Nullable<int> _ekleyen_tc;
		
		private string _icerik;
		
		private System.Nullable<int> _musteri_id;
		
		private System.Nullable<System.DateTime> _eklenen_tarih;
		
		public Notlar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_id", DbType="NChar(10)")]
		public string n_id
		{
			get
			{
				return this._n_id;
			}
			set
			{
				if ((this._n_id != value))
				{
					this._n_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ekleyen_tc", DbType="Int")]
		public System.Nullable<int> ekleyen_tc
		{
			get
			{
				return this._ekleyen_tc;
			}
			set
			{
				if ((this._ekleyen_tc != value))
				{
					this._ekleyen_tc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icerik", DbType="NVarChar(MAX)")]
		public string icerik
		{
			get
			{
				return this._icerik;
			}
			set
			{
				if ((this._icerik != value))
				{
					this._icerik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteri_id", DbType="Int")]
		public System.Nullable<int> musteri_id
		{
			get
			{
				return this._musteri_id;
			}
			set
			{
				if ((this._musteri_id != value))
				{
					this._musteri_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eklenen_tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> eklenen_tarih
		{
			get
			{
				return this._eklenen_tarih;
			}
			set
			{
				if ((this._eklenen_tarih != value))
				{
					this._eklenen_tarih = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonelTablosu")]
	public partial class PersonelTablosu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _p_id;
		
		private string _tc;
		
		private string _ad;
		
		private string _soyad;
		
		private string _cinsiyet;
		
		private System.Nullable<System.DateTime> _dogum_tarihi;
		
		private string _pozisyonu;
		
		private string _tel1;
		
		private string _tel2;
		
		private string _ep1;
		
		private string _ep2;
		
		private string _adres;
		
		private string _il;
		
		private string _ilce;
		
		private System.Nullable<int> _yetki;
		
		private string _sifre;
		
		private System.Data.Linq.Binary _cv;
		
		private string _posta_kodu;
		
		private System.Data.Linq.Binary _foto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_idChanging(int value);
    partial void Onp_idChanged();
    partial void OntcChanging(string value);
    partial void OntcChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void OncinsiyetChanging(string value);
    partial void OncinsiyetChanged();
    partial void Ondogum_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Ondogum_tarihiChanged();
    partial void OnpozisyonuChanging(string value);
    partial void OnpozisyonuChanged();
    partial void Ontel1Changing(string value);
    partial void Ontel1Changed();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void Onep1Changing(string value);
    partial void Onep1Changed();
    partial void Onep2Changing(string value);
    partial void Onep2Changed();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OnilChanging(string value);
    partial void OnilChanged();
    partial void OnilceChanging(string value);
    partial void OnilceChanged();
    partial void OnyetkiChanging(System.Nullable<int> value);
    partial void OnyetkiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OncvChanging(System.Data.Linq.Binary value);
    partial void OncvChanged();
    partial void Onposta_koduChanging(string value);
    partial void Onposta_koduChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    #endregion
		
		public PersonelTablosu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int p_id
		{
			get
			{
				return this._p_id;
			}
			set
			{
				if ((this._p_id != value))
				{
					this.Onp_idChanging(value);
					this.SendPropertyChanging();
					this._p_id = value;
					this.SendPropertyChanged("p_id");
					this.Onp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc", DbType="NVarChar(11)")]
		public string tc
		{
			get
			{
				return this._tc;
			}
			set
			{
				if ((this._tc != value))
				{
					this.OntcChanging(value);
					this.SendPropertyChanging();
					this._tc = value;
					this.SendPropertyChanged("tc");
					this.OntcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50)")]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50)")]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this.OnsoyadChanging(value);
					this.SendPropertyChanging();
					this._soyad = value;
					this.SendPropertyChanged("soyad");
					this.OnsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="NVarChar(50)")]
		public string cinsiyet
		{
			get
			{
				return this._cinsiyet;
			}
			set
			{
				if ((this._cinsiyet != value))
				{
					this.OncinsiyetChanging(value);
					this.SendPropertyChanging();
					this._cinsiyet = value;
					this.SendPropertyChanged("cinsiyet");
					this.OncinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogum_tarihi", DbType="Date")]
		public System.Nullable<System.DateTime> dogum_tarihi
		{
			get
			{
				return this._dogum_tarihi;
			}
			set
			{
				if ((this._dogum_tarihi != value))
				{
					this.Ondogum_tarihiChanging(value);
					this.SendPropertyChanging();
					this._dogum_tarihi = value;
					this.SendPropertyChanged("dogum_tarihi");
					this.Ondogum_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pozisyonu", DbType="NVarChar(50)")]
		public string pozisyonu
		{
			get
			{
				return this._pozisyonu;
			}
			set
			{
				if ((this._pozisyonu != value))
				{
					this.OnpozisyonuChanging(value);
					this.SendPropertyChanging();
					this._pozisyonu = value;
					this.SendPropertyChanged("pozisyonu");
					this.OnpozisyonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="NVarChar(20)")]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this.Ontel1Changing(value);
					this.SendPropertyChanging();
					this._tel1 = value;
					this.SendPropertyChanged("tel1");
					this.Ontel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ep1", DbType="NVarChar(MAX)")]
		public string ep1
		{
			get
			{
				return this._ep1;
			}
			set
			{
				if ((this._ep1 != value))
				{
					this.Onep1Changing(value);
					this.SendPropertyChanging();
					this._ep1 = value;
					this.SendPropertyChanged("ep1");
					this.Onep1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ep2", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ep2
		{
			get
			{
				return this._ep2;
			}
			set
			{
				if ((this._ep2 != value))
				{
					this.Onep2Changing(value);
					this.SendPropertyChanging();
					this._ep2 = value;
					this.SendPropertyChanged("ep2");
					this.Onep2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(MAX)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_il", DbType="NVarChar(MAX)")]
		public string il
		{
			get
			{
				return this._il;
			}
			set
			{
				if ((this._il != value))
				{
					this.OnilChanging(value);
					this.SendPropertyChanging();
					this._il = value;
					this.SendPropertyChanged("il");
					this.OnilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilce", DbType="NVarChar(MAX)")]
		public string ilce
		{
			get
			{
				return this._ilce;
			}
			set
			{
				if ((this._ilce != value))
				{
					this.OnilceChanging(value);
					this.SendPropertyChanging();
					this._ilce = value;
					this.SendPropertyChanged("ilce");
					this.OnilceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetki", DbType="Int")]
		public System.Nullable<int> yetki
		{
			get
			{
				return this._yetki;
			}
			set
			{
				if ((this._yetki != value))
				{
					this.OnyetkiChanging(value);
					this.SendPropertyChanging();
					this._yetki = value;
					this.SendPropertyChanged("yetki");
					this.OnyetkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cv", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary cv
		{
			get
			{
				return this._cv;
			}
			set
			{
				if ((this._cv != value))
				{
					this.OncvChanging(value);
					this.SendPropertyChanging();
					this._cv = value;
					this.SendPropertyChanged("cv");
					this.OncvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posta_kodu", DbType="NChar(10)")]
		public string posta_kodu
		{
			get
			{
				return this._posta_kodu;
			}
			set
			{
				if ((this._posta_kodu != value))
				{
					this.Onposta_koduChanging(value);
					this.SendPropertyChanging();
					this._posta_kodu = value;
					this.SendPropertyChanged("posta_kodu");
					this.Onposta_koduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
